# Generated by Django 5.1.2 on 2024-11-29 15:28

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Migration to rename the 'name' field to 'first_name' and add the 'last_name' field to the User model.
    """

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]