from django.db import models

"""
ChatBot Management Models
Handles chat session data storage and tracking.

This module provides:
- Chat session history storage
- Query and response tracking
- Timestamp management for conversations
"""


class ChatSession(models.Model):
    """
    Model representing a chat interaction session.
    
    Attributes:
        course_name (CharField): Name of the course the chat is related to
        user_query (TextField): The question asked by the user
        gpt_response (TextField): The response generated by GPT
        timestamp (DateTimeField): When the chat occurred
    """
    course_name = models.CharField(max_length=255)
    user_query = models.TextField()
    gpt_response = models.TextField()  # Storing GPT-4's response
    timestamp = models.DateTimeField(auto_now_add=True)  # Track when the chat occurred

    def __str__(self):
        """
        String representation of the chat session.

        Returns:
            str: Description including course name, query, and timestamp
        """
        return f"{self.course_name}: {self.user_query} at {self.timestamp}"
