# Generated by Django 5.1.2 on 2024-11-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(default='01', max_length=255)),
                ('department', models.CharField(default='NA', max_length=255)),
                ('semester', models.CharField(default='fall2024', max_length=255)),
                ('course_number', models.IntegerField(default=0)),
                ('pin', models.CharField(max_length=255)),
                ('professor', models.CharField(max_length=255)),
            ],
        ),
    ]
