# Generated by Django 5.1.2 on 2024-11-28 20:48

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Migration to add the 'is_active' field to the Course model.
    """

    dependencies = [
        ('class_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]