# Generated by Django 5.1.2 on 2024-11-29 00:49

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Migration to add the 'credits' field to the Course model.
    """

    dependencies = [
        ('class_management', '0002_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=4),
        ),
    ]