# Generated by Django 5.1.4 on 2024-12-10 00:20

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Migration to add the 'last_updated' field to the Course model.
    """

    dependencies = [
        ('class_management', '0003_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]