# Generated by Django 5.1.4 on 2024-12-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentenrollments',
            old_name='student_id',
            new_name='student',
        ),
    ]
