# Generated by Django 5.1.4 on 2024-12-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_rename_student_id_studentenrollments_student'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentenrollments',
            managers=[
            ],
        ),
    ]
