# Generated by Django 5.1.2 on 2024-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='file_type',
            field=models.CharField(default='docx', max_length=50),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='size',
            field=models.IntegerField(default=5000),
        ),
    ]
